### ISSUE TITLE
Request for update contracts into 0.6.5

### ISSUE THREAD

**Issue by noyonthe1** [OpenZeppelin/openzeppelin-contracts-ethereum-package#81] opened 2020-04-14 03:58 UTC
We are working on updating the solidity version from `0.5.16` to `0.6.5`
`pragma solidity 0.6.5;`
When changing the `solc` version and contract solidity version we got an issue as are using ownable.sol from `"@openzeppelin/contracts-ethereum-package": "^2.5.0"` in our project. 
When openzeppelin/contracts-ethereum-package package gonna support new solitidy version and updated ownable into `0.6.5`  

https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package/blob/bf0277b398c0454276bd8caf0ee35efaf46e686b/contracts/ownership/Ownable.sol#L1

**Comment by abcoathup** [comment] 2020-04-14 08:17
Hi @noyonthe1,
This is a duplicate of #79
Please see that issue for the latest status.

**Closed by abcoathup** 2020-04-14 08:17 UTC
